Name: Tianzheng Li
CPSC 483-01 Project 1 // Spring 2021

	1. Working as intended.The .csv file will be converted into a list through 'import csv' and be displayed through pandas' 'DataFrame'. 
	2. Working as intended. Quartiles for Week 1 will be displayed, which will be constructed (through 'construct_week()' function) and require sorting (through the function 'sort_list()') and finally the 'quartiles()' function.
	3. Working as intended. The Turkey Fences will be found and displayed through the 'turkey_fences()' function and be used to find the outliers (function 'outliers()').
	4. Working as intended. All previously mentioned functions will be consolidated into a single function 'week_data()' so that it can be called to easily display all data for the desired week.
	5. Working as intended. All weeks are further consolidated into function 'tardy()' so that the students determined to be tardy are displayed into a single table of their own, sorted by their original order from 'participants.csv'

In [1]:
# by Tianzheng Li

import csv
from pandas import DataFrame

# ======================
# All functions
# ======================

# Seperates data into individual weeks
def construct_week(data_total, week, length):
    data_new = []
    for i in range(0, length):
        data_new.append('')
        data_new[i] = [int(data_total[i][week]), data_total[i][0]]
    return data_new
        
# Sorts and reverses the list
def sort_list(data_old, length):
    data_old.sort()
    data_new = []
    for i in range(0, length):
        data_new.append('')
        data_new[i] = [data_old[i][1], data_old[i][0]]
    return data_new

# Quartiles
def quartiles(data_old, length):
    # even
    if length % 2 == 0:
        half = int((length / 2)) - 1
        median = (data_old[half][1] + data_old[half + 1][1]) / 2
    # odd
    else:
        half = (round(length / 2)) - 1
        median = data_old[half][1]
    half += 1
    # even
    if half % 2 == 0:
        quarter = int((half / 2)) - 1
        lower_q = (data_old[quarter][1] + data_old[quarter + 1][1]) / 2
    # odd
    else:
        quarter = (round(half / 2)) - 1
        lower_q = data_old[quarter][1]
    quarter += 1
    third_quarter = (half + quarter) - 1
    # even
    if half % 2 == 0:
        upper_q = ((data_old[third_quarter][1]) + data_old[third_quarter + 1][1]) / 2
    # odd
    else:
        upper_q = data_old[third_quarter][1]
        
    print("\033[1mLower Quartile: \033[0m" + str(lower_q))
    print("\033[1mMedian: \033[0m" + str(median))
    print("\033[1mUpper Quartile: \033[0m" + str(upper_q))
    
    q_list = [lower_q, median, upper_q]
    return q_list

# Turkey Fences
def turkey_fences(lower_q, upper_q):
    lower_limit = lower_q - (1.5 * (upper_q - lower_q))
    upper_limit = upper_q + (1.6 * (upper_q - lower_q))
    print("\033[1mTurkey's Fences: \033[0m[" + str(lower_limit) + ", " + str(upper_limit) + "]")
    limits = [lower_limit, upper_limit]
    return limits

# Outliers
def outliers(data_old, lower, upper):
    o_list = []
    index = 0
    for i in range(0, len(data_old)):
        if data_old[i][1] < lower or data_old[i][1] > upper:
            o_list.append('')
            o_list[index] = data_old[i]
            index += 1
    print("\033[1mOutliers: \033[0m" + str(o_list))
    return o_list

# Prints all data for the week (The table, the quartiles, the turkey fences, and outliers)
def week_data(data_old, week_no, length):
    print("\033[1mWeek " + str(week_no) + " Data\033[0m")
    
    week_0 = construct_week(data, week_no, length)
    week_0_sorted = sort_list(week_0, length)
    
    df = DataFrame(week_0_sorted)
    df.columns = ['Name', 'Minutes']
    print(df)
    print()
    
    quartiles_0 = quartiles(week_0_sorted, length)
    print()
    
    limits_0 = turkey_fences(quartiles_0[0], quartiles_0[2])
    print()
    
    outliers_0 = outliers(week_0_sorted, limits_0[0], limits_0[1])
    print()
    
    w_data = [quartiles_0, limits_0, outliers_0]
    return w_data

# Prints all data for all weeks, specifically to find those who are tardy
def tardy(data_old, length):
    # Week 1
    w_1_data = week_data(data_old, 1, length)
    print("\033[1m=====================================\033[0m\n")
    # Week 2
    w_2_data = week_data(data_old, 2, length)
    print("\033[1m=====================================\033[0m\n")
    # Week 3
    w_3_data = week_data(data_old, 3, length)
    
    print("\033[1m=====================================\033[0m\n")
    print("\033[1mAll Outliers\033[0m")
    data_new = []
    index = 0
    for i in range(0, length):
        for j in range(0, len(w_1_data)):
            if data_old[i][0] == w_1_data[2][j][0]:
                data_new.append('')
                data_new[index] = data_old[i]
                index += 1
        for j in range(0, len(w_2_data)):
            if data_old[i][0] == w_2_data[2][j][0]:
                data_new.append('')
                data_new[index] = data_old[i]
                index += 1
        for j in range(0, len(w_3_data)):
            if data_old[i][0] == w_3_data[2][j][0]:
                data_new.append('')
                data_new[index] = data_old[i]
                index += 1
    
    df = DataFrame(data_new)
    df.columns = ['Name', '1', '2', '3']
    print(df)
    print()

In [2]:
# Convert .csv to list
with open('participants.csv', newline = '') as f:
    reader = csv.reader(f)
    data = list(reader)
data.pop(0)
data_length = len(data)

# participants.csv original table
df = DataFrame(data)
df.columns = ['Name', '1', '2', '3']
print(df)

                  Name    1    2    3
0        Nora Rutledge  159  170  179
1           Reef Tapia  163  169  174
2       Kaleb Cummings  156  170   51
3      Sameera Knowles  165  168  178
4        Chelsea Wiley  170  174  174
5         Kezia Graham  159  171  177
6     Samiyah Robinson  163  167  173
7            Trey Khan  110   66  183
8          Jarrod Moon  167  170  170
9       Hasan Goulding  168  170  175
10      Pooja Thornton  157  169  177
11         Taya Curtis  115   74  178
12       Wallace Rojas   91   35  180
13        Arif Gardner  172  175  170
14      Ameerah Fulton  158  175   24
15       Sabah Houston  159  168  183
16      Mikhail Ashton  155  171  177
17          Penny Bass  167  168  178
18  Brandon-Lee Bowers  171  175  175
19    Isadora Erickson  169  171  175
20      Stephanie Hail  156  143  174
21       Shelley Wells  160  161  181
22       Scarlet Cross  160  164  180
23         Gideon Read  167  175  176
24       Berat Langley  165  174  174
25        Gerrard Soto  171  173  175
26       Elyse Richard  168  174  175
27       Mikolaj Meyer  176  195  179
28        Arman Mackie  157  175    9
29      Ellouise Reyes  165  174  170
30     Emelie Delacruz  166  175  175
31     Ricky Humphreys  164  169  180

In [3]:
# Week 1 Data
week_1_data = week_data(data, 1, data_length)

Week 1 Data
                  Name  Minutes
0        Wallace Rojas       91
1            Trey Khan      110
2          Taya Curtis      115
3       Mikhail Ashton      155
4       Kaleb Cummings      156
5       Stephanie Hail      156
6         Arman Mackie      157
7       Pooja Thornton      157
8       Ameerah Fulton      158
9         Kezia Graham      159
10       Nora Rutledge      159
11       Sabah Houston      159
12       Scarlet Cross      160
13       Shelley Wells      160
14          Reef Tapia      163
15    Samiyah Robinson      163
16     Ricky Humphreys      164
17       Berat Langley      165
18      Ellouise Reyes      165
19     Sameera Knowles      165
20     Emelie Delacruz      166
21         Gideon Read      167
22         Jarrod Moon      167
23          Penny Bass      167
24       Elyse Richard      168
25      Hasan Goulding      168
26    Isadora Erickson      169
27       Chelsea Wiley      170
28  Brandon-Lee Bowers      171
29        Gerrard Soto      171
30        Arif Gardner      172
31       Mikolaj Meyer      176

Lower Quartile: 157.5
Median: 163.5
Upper Quartile: 167.5

Turkey's Fences: [142.5, 183.5]

Outliers: [['Wallace Rojas', 91], ['Trey Khan', 110], ['Taya Curtis', 115]]

In [4]:
# Week 2 Data
week_2_data = week_data(data, 2, data_length)

Week 2 Data
                  Name  Minutes
0        Wallace Rojas       35
1            Trey Khan       66
2          Taya Curtis       74
3       Stephanie Hail      143
4        Shelley Wells      161
5        Scarlet Cross      164
6     Samiyah Robinson      167
7           Penny Bass      168
8        Sabah Houston      168
9      Sameera Knowles      168
10      Pooja Thornton      169
11          Reef Tapia      169
12     Ricky Humphreys      169
13      Hasan Goulding      170
14         Jarrod Moon      170
15      Kaleb Cummings      170
16       Nora Rutledge      170
17    Isadora Erickson      171
18        Kezia Graham      171
19      Mikhail Ashton      171
20        Gerrard Soto      173
21       Berat Langley      174
22       Chelsea Wiley      174
23      Ellouise Reyes      174
24       Elyse Richard      174
25      Ameerah Fulton      175
26        Arif Gardner      175
27        Arman Mackie      175
28  Brandon-Lee Bowers      175
29     Emelie Delacruz      175
30         Gideon Read      175
31       Mikolaj Meyer      195

Lower Quartile: 168.0
Median: 170.0
Upper Quartile: 174.0

Turkey's Fences: [159.0, 183.6]

Outliers: [['Wallace Rojas', 35], ['Trey Khan', 66], ['Taya Curtis', 74], ['Stephanie Hail', 143], ['Mikolaj Meyer', 195]]

In [5]:
# Week 3 Data
week_3_data = week_data(data, 3, data_length)

Week 3 Data
                  Name  Minutes
0         Arman Mackie        9
1       Ameerah Fulton       24
2       Kaleb Cummings       51
3         Arif Gardner      170
4       Ellouise Reyes      170
5          Jarrod Moon      170
6     Samiyah Robinson      173
7        Berat Langley      174
8        Chelsea Wiley      174
9           Reef Tapia      174
10      Stephanie Hail      174
11  Brandon-Lee Bowers      175
12       Elyse Richard      175
13     Emelie Delacruz      175
14        Gerrard Soto      175
15      Hasan Goulding      175
16    Isadora Erickson      175
17         Gideon Read      176
18        Kezia Graham      177
19      Mikhail Ashton      177
20      Pooja Thornton      177
21          Penny Bass      178
22     Sameera Knowles      178
23         Taya Curtis      178
24       Mikolaj Meyer      179
25       Nora Rutledge      179
26     Ricky Humphreys      180
27       Scarlet Cross      180
28       Wallace Rojas      180
29       Shelley Wells      181
30       Sabah Houston      183
31           Trey Khan      183

Lower Quartile: 174.0
Median: 175.0
Upper Quartile: 178.5

Turkey's Fences: [167.25, 185.7]

Outliers: [['Arman Mackie', 9], ['Ameerah Fulton', 24], ['Kaleb Cummings', 51]]

In [6]:
# Constructs tardy, searching through all three weeks to find outliers and putting them into a table
tardy(data, data_length)

Week 1 Data
                  Name  Minutes
0        Wallace Rojas       91
1            Trey Khan      110
2          Taya Curtis      115
3       Mikhail Ashton      155
4       Kaleb Cummings      156
5       Stephanie Hail      156
6         Arman Mackie      157
7       Pooja Thornton      157
8       Ameerah Fulton      158
9         Kezia Graham      159
10       Nora Rutledge      159
11       Sabah Houston      159
12       Scarlet Cross      160
13       Shelley Wells      160
14          Reef Tapia      163
15    Samiyah Robinson      163
16     Ricky Humphreys      164
17       Berat Langley      165
18      Ellouise Reyes      165
19     Sameera Knowles      165
20     Emelie Delacruz      166
21         Gideon Read      167
22         Jarrod Moon      167
23          Penny Bass      167
24       Elyse Richard      168
25      Hasan Goulding      168
26    Isadora Erickson      169
27       Chelsea Wiley      170
28  Brandon-Lee Bowers      171
29        Gerrard Soto      171
30        Arif Gardner      172
31       Mikolaj Meyer      176

Lower Quartile: 157.5
Median: 163.5
Upper Quartile: 167.5

Turkey's Fences: [142.5, 183.5]

Outliers: [['Wallace Rojas', 91], ['Trey Khan', 110], ['Taya Curtis', 115]]

=====================================

Week 2 Data
                  Name  Minutes
0        Wallace Rojas       35
1            Trey Khan       66
2          Taya Curtis       74
3       Stephanie Hail      143
4        Shelley Wells      161
5        Scarlet Cross      164
6     Samiyah Robinson      167
7           Penny Bass      168
8        Sabah Houston      168
9      Sameera Knowles      168
10      Pooja Thornton      169
11          Reef Tapia      169
12     Ricky Humphreys      169
13      Hasan Goulding      170
14         Jarrod Moon      170
15      Kaleb Cummings      170
16       Nora Rutledge      170
17    Isadora Erickson      171
18        Kezia Graham      171
19      Mikhail Ashton      171
20        Gerrard Soto      173
21       Berat Langley      174
22       Chelsea Wiley      174
23      Ellouise Reyes      174
24       Elyse Richard      174
25      Ameerah Fulton      175
26        Arif Gardner      175
27        Arman Mackie      175
28  Brandon-Lee Bowers      175
29     Emelie Delacruz      175
30         Gideon Read      175
31       Mikolaj Meyer      195

Lower Quartile: 168.0
Median: 170.0
Upper Quartile: 174.0

Turkey's Fences: [159.0, 183.6]

Outliers: [['Wallace Rojas', 35], ['Trey Khan', 66], ['Taya Curtis', 74], ['Stephanie Hail', 143], ['Mikolaj Meyer', 195]]

=====================================

Week 3 Data
                  Name  Minutes
0         Arman Mackie        9
1       Ameerah Fulton       24
2       Kaleb Cummings       51
3         Arif Gardner      170
4       Ellouise Reyes      170
5          Jarrod Moon      170
6     Samiyah Robinson      173
7        Berat Langley      174
8        Chelsea Wiley      174
9           Reef Tapia      174
10      Stephanie Hail      174
11  Brandon-Lee Bowers      175
12       Elyse Richard      175
13     Emelie Delacruz      175
14        Gerrard Soto      175
15      Hasan Goulding      175
16    Isadora Erickson      175
17         Gideon Read      176
18        Kezia Graham      177
19      Mikhail Ashton      177
20      Pooja Thornton      177
21          Penny Bass      178
22     Sameera Knowles      178
23         Taya Curtis      178
24       Mikolaj Meyer      179
25       Nora Rutledge      179
26     Ricky Humphreys      180
27       Scarlet Cross      180
28       Wallace Rojas      180
29       Shelley Wells      181
30       Sabah Houston      183
31           Trey Khan      183

Lower Quartile: 174.0
Median: 175.0
Upper Quartile: 178.5

Turkey's Fences: [167.25, 185.7]

Outliers: [['Arman Mackie', 9], ['Ameerah Fulton', 24], ['Kaleb Cummings', 51]]

=====================================

All Outliers
             Name    1    2    3
0  Kaleb Cummings  156  170   51
1       Trey Khan  110   66  183
2       Trey Khan  110   66  183
3     Taya Curtis  115   74  178
4     Taya Curtis  115   74  178
5   Wallace Rojas   91   35  180
6   Wallace Rojas   91   35  180
7  Ameerah Fulton  158  175   24
8    Arman Mackie  157  175    9